### ISSUE TITLE
Issue lies in accessing classes from the BlueStackSDK framework version 4.4.4 and 4.4.5

### ISSUE THREAD

**Issue by nhenri** [azerion/BlueStackSDK#40]
Since the update of Bluestack to 4.4.4 and 4.4.5, we no longer have access to several classes of the BlueStackSDK framework such as MNGAdsSDKFactory, MNGAdsAdapterInterstitialDelegate, etc...

After checking the content of the BlueStackSDK package on versions 4.4.4 and 4.4.5, here is the content:
<img width="611" alt="BlueStackSDK_4 4 4_4 4 5" src="https://github.com/azerion/BlueStackSDK/assets/637964/14dc1496-9726-4479-b4f9-31088d696455">

And on version 4.4.3, the BlueStackSDK content is as follows:
<img width="659" alt="BlueStackSDK_4 4 3" src="https://github.com/azerion/BlueStackSDK/assets/637964/9b5efd17-ec62-4b35-993b-3f1f6b440c5b">

Thank you for looking

**Comment by torongo-azerion** [comment]
@nhenri 
We have released BlueStack-SDK version 4.4.6 with the fix.

**Comment by nhenri** [comment]
@torongo-azerion Thank you, version 4.4.6 fixes the issue.
